### ISSUE TITLE
Julia Logo Colors in Hex

### ISSUE THREAD

**Issue by jpfairbanks** [JuliaGraphics/julia-logo-graphics#2]
Can we add the hex versions of these colors to this repo? I think that would help people use the logo colors in programs that don't take RGB{Float64} or named colors.

**Comment by jpfairbanks** [comment]
Here is the answer, so I guess people could just refer to this issue

```
julia> Colorshex(RGB(lighter_green...))
"60AD51"

julia> Colors.hex(RGB(darker_green...))
"389826"

julia> Colors.hex(RGB(darker_red...))
"CB3C33"

julia> Colors.hex(RGB(lighter_red...))
"D5635C"

julia> Colors.hex(RGB(lighter_purple...))
"AA79C1"

julia> Colors.hex(RGB(darker_purple...))
"9558B2"

julia> Colors.hex(RGB(darker_blue...))
"4063D8"

julia> Colors.hex(RGB(lighter_blue...))
"6682E0"
```

**Comment by cormullion** [comment]
Good idea. I'll update it one rainy day.

Oh, it's raining... :) https://github.com/JuliaGraphics/julia-logo-graphics/commit/c8627fd439c4a9f99fb05500b40d85e98523151d

**Comment by jpfairbanks** [comment]
Thanks!
