### ISSUE TITLE
Favicon

### ISSUE THREAD

**Issue by mortenpi** [JuliaGraphics/julia-logo-graphics#5]
Could we also have a `favicon.ico` version of the three dots? It's subtle, but the [docs.julialang.org favicon](https://docs.julialang.org/favicon.ico) still has the rings.

**Comment by cormullion** [comment]
Is that the same as [this one](https://github.com/JuliaLang/julia/blob/master/contrib/windows/julia.ico) (ie a Windows .ico file)? I get really confused about favicons and ico files...

**Comment by mortenpi** [comment]
Oh yea, that's it I think. I PRed that to docs.julialang.org. A copy could be store here as well I guess?

**Comment by cormullion** [comment]
Good plan! Added.
